import { m } from '@world/units';
import {
  DT,
  DRIVER_NOISE,
  FLEET_CEILING,
  JAM_GAP,
  TRAFFIC_DENSITY,
} from '../params';
import type { SimWorld } from '../world';
import { ARCHETYPES, type Archetype, archetypeWeights, bodyClassOfArchetype } from './archetypes';
import { makeDriver } from './driver';
import { idmAccel } from './idm';
import { createVehicle, snapshot, type Vehicle } from './state';
import { planFrom } from '../routing/router';
import { chooseVehicleDestination } from '../routing/destination';
import { assignOccupancy } from './kerbStops';
import { curveSpeedCap } from './curvature';

/**
 * Arrival rate at one boundary entry lane, vehicles per second, at traffic
 * intensity and demand 1 (about 180 an hour a lane, a quiet city street).
 */
export const ENTRY_RATE = 0.05;
/** Vehicles an entry holds outside the map before further arrivals are lost. */
export const ENTRY_QUEUE = 6;
/**
 * Arrivals a second at one entry with a number of cars chosen
 * (`SimWorld.trafficCount`) once the map holds it: a car that leaves is soon
 * replaced. Below the number every entry is saturated (`stepDispatch`).
 */
const FILL_RATE = 0.25;
/** Most vehicles admitted onto the map in one tick, city-wide. */
const ADMIT_PER_TICK = 4;

/**
 * Density ceiling on the fleet, from total road length.
 *
 * Traffic is generated by demand at each entry (`stepDispatch`); this only
 * stops a saturated map from growing without bound, which would cost frame
 * rate without adding anything a player could see. `FLEET_CEILING` is a
 * runaway guard far above it.
 */
export function trafficTarget(w: SimWorld): number {
  let total = 0;
  for (const ribbon of w.net.ribbons.values()) total += ribbon.full.length;
  // The number chosen; past one car per 12 m of road they would only stand
  // bumper to bumper, so not more than that.
  if (w.trafficCount !== null) return Math.min(FLEET_CEILING, Math.max(0, Math.round(w.trafficCount)), Math.floor(total / m(12)));
  const ceiling = Math.floor(FLEET_CEILING * w.populationShare);
  return Math.min(
    ceiling,
    Math.floor(total * TRAFFIC_DENSITY * w.trafficIntensity * w.demandMultiplier),
  );
}

/** Lane entries at the edge of the map, where traffic arrives from outside. */
function entryLanes(w: SimWorld): string[] {
  const out: string[] = [];
  for (const lane of w.graph.lanelets.values()) {
    if (lane.kind !== 'link' || lane.length < 30) continue;
    if (w.rt(lane.id).ghost) continue;
    if (lane.from !== undefined && w.doc.mapEdge(lane.from)) out.push(lane.id);
  }
  return out.sort();
}

/** Seconds to the next arrival of a Poisson stream of `rate` per second. */
function nextGap(w: SimWorld, rate: number): number {
  return -Math.log(1 - w.rng.spawnVehicles.float()) / Math.max(rate, 1e-9);
}

/**
 * Brings traffic in at the edges of the map.
 *
 * This used to be ONE attempt every half second for the whole city, placed at
 * whichever entry was least occupied: however many roads led into the map,
 * no more than two vehicles a second could arrive, and the traffic went
 * wherever the map was emptiest rather than where it was coming from. Every
 * boundary entry lane now has its own arrival stream. An arrival that finds
 * its entry full waits outside the map rather than vanishing, up to
 * `ENTRY_QUEUE` vehicles; when there is room, the arrivals that have waited
 * longest anywhere in the city come in first.
 */
export function stepDispatch(w: SimWorld, enabled: boolean): void {
  // A city with residents drives its own cars (`sim/city`): none come in.
  if (!w.edgeTraffic) return;
  if (!enabled) return;
  w.vehicleSpawnClock += DT;
  const now = w.vehicleSpawnClock;
  // A number of cars chosen (`SimWorld.trafficCount`): while the map has
  // fewer, every entry has a car waiting to come in, let in as soon as its
  // lane has room behind the last one (`spawnAt`) - SUMO's insertion
  // backlog, so the entry carries what its lane takes (sumo.dlr.de
  // "RoadCapacity": about 1 200 cars an hour a lane at the default insertion,
  // up to 2 500). A stream of one car every four seconds an entry (900 an
  // hour) never reached the number on a map with few roads in: the test
  // city's three entry lanes held about 160 cars at 400 chosen, as many as
  // left.
  const saturated = w.trafficCount !== null && w.trafficCount > 0 && w.vehicles.size < trafficTarget(w);
  const rate = w.trafficCount !== null ? (w.trafficCount > 0 ? FILL_RATE : 0)
    : ENTRY_RATE * w.trafficIntensity * w.demandMultiplier;
  const entries = entryLanes(w);

  const live = new Set(entries);
  for (const id of [...w.entryDemand.keys()]) if (!live.has(id)) w.entryDemand.delete(id);

  for (const id of entries) {
    let demand = w.entryDemand.get(id);
    if (!demand) {
      demand = { next: rate > 0 ? now + nextGap(w, rate) : Infinity, rate, waiting: [] };
      w.entryDemand.set(id, demand);
    }
    // The slider moved: the wait still to run is rescaled to the new rate, or
    // drawn afresh when there was none (audit P1-20). At 0 % the next arrival
    // used to be drawn ~10^9 s away, and raising the slider again left it
    // there: the entry stayed dead for good.
    if (demand.rate !== rate) {
      demand.next = rate <= 0 ? Infinity
        : demand.rate > 0 && Number.isFinite(demand.next) ? now + (demand.next - now) * (demand.rate / rate)
          : now + nextGap(w, rate);
      demand.rate = rate;
    }
    if (rate <= 0) continue;
    if (saturated && demand.waiting.length === 0) demand.waiting.push(now);
    while (demand.next <= now) {
      if (demand.waiting.length < ENTRY_QUEUE) demand.waiting.push(demand.next);
      else w.entryDemandLost++;
      demand.next += nextGap(w, rate);
    }
  }

  const cap = trafficTarget(w);
  const blocked = new Set<string>();
  for (let admitted = 0; admitted < ADMIT_PER_TICK && w.vehicles.size < cap; admitted++) {
    // Oldest waiting arrival first, anywhere on the map; ties by lane id.
    let best: string | null = null;
    let bestAt = Infinity;
    for (const id of entries) {
      if (blocked.has(id)) continue;
      const at = w.entryDemand.get(id)?.waiting[0];
      if (at !== undefined && at < bestAt) {
        best = id;
        bestAt = at;
      }
    }
    if (best === null) break;
    if (spawnAt(w, best)) w.entryDemand.get(best)?.waiting.shift();
    else blocked.add(best);
  }
}

/**
 * Spawns one vehicle at the first entry lane with room for it. Kept for
 * harnesses that place traffic directly; the running game uses
 * `stepDispatch`.
 */
export function spawnVehicle(w: SimWorld): boolean {
  for (const id of entryLanes(w)) if (spawnAt(w, id)) return true;
  return false;
}

/**
 * Puts one vehicle on the map at the start of an entry lane, if the lane has
 * room behind whatever is already on it.
 *
 * Only ever at an edge of the map: materialising a car halfway along a street
 * is both visually jarring and physically false, so a closed network with no
 * boundary entry receives no traffic until the player connects one.
 */
function spawnAt(w: SimWorld, id: string): boolean {
  const lane = w.lanelet(id);
  if (!lane) return false;
  const arch = w.rng.spawnVehicles.weighted(archetypeWeights()) as Archetype;
  // A bus lane is buses only (docs/VIAS.md V4).
  if (!w.graph.laneUsable(id, arch.shape)) return false;
  // Do not materialise a bus on an entry whose junction has no movement its
  // body can physically take. A later weighted draw may choose a smaller car.
  if (lane.to !== undefined && w.doc.degree(lane.to) > 1 &&
      w.graph.exitsOf(id).every((exit) =>
        (w.connector(exit)?.maxBodyClass ?? -1) < bodyClassOfArchetype(arch))) return false;
  // The tail includes a body still sliding out of this lane.
  let tailRear = Infinity;
  let tailSpeed = Infinity;
  for (const body of w.bodiesIn(id)) {
    const rear = body.s - body.vehicle.archetype.length;
    if (rear < tailRear) {
      tailRear = rear;
      tailSpeed = body.vehicle.v;
    }
  }
  const entryClearance = Math.max(0.5, Math.min(1.5, arch.width / 4));
  // `s` is the front of the vehicle. Its rear must be on the authored road
  // at birth; the entry node has no lanelet behind it to carry the body.
  if (lane.length <= arch.length + entryClearance) return false;
  if (tailRear < arch.length + entryClearance + JAM_GAP) return false;
  // Nor onto people: the end of a road that leads off the map is where they
  // cross from one footway to the other (`world/walkways.ts`, unmarked).
  for (const s of [0, (arch.length + entryClearance) / 2, arch.length + entryClearance]) {
    const f = lane.centre.sampleAt(Math.min(lane.length, s));
    if (w.pedEngine.bridge.anyoneWithin(w, f.p.x, f.p.y, arch.width / 2 + m(1), null)) return false;
  }

  // The driver is drawn BEFORE the free-flow speed and from the same stream,
  // so the two are part of one personality rather than two independent rolls.
  const driver = makeDriver(arch, () => w.rng.driver.float());
  const v0 =
    lane.speedLimit *
    arch.speedFactor *
    w.rng.driver.range(DRIVER_NOISE.lo, DRIVER_NOISE.hi) *
    // A pushy driver wants more than the limit and a timid one less, on top
    // of the ordinary spread. Without it every driver in the fleet converges
    // on the same cruise and the only thing distinguishing them is how they
    // got there.
    (1 + driver.aggression * 0.07);

  const palette = arch.palette;
  const color = palette[Math.floor(w.rng.spawnVehicles.float() * palette.length)] as string;

  const vehicle = createVehicle(w.nextVehicleId++, arch, driver, color, id, v0, w.clock.tick);
  vehicle.s = arch.length + entryClearance;
  vehicle.v = birthSpeed(driver, v0, Math.min(v0 * 0.4, lane.speedLimit * 0.4),
    tailRear - vehicle.s, tailSpeed);
  vehicle.prev = snapshot(vehicle);

  assignOccupancy(w, vehicle);

  w.vehicles.set(vehicle.id, vehicle);
  w.enterLanelet(vehicle, id);
  vehicle.destination = chooseVehicleDestination(w, id, bodyClassOfArchetype(vehicle.archetype));
  // The check above sees only the first movement; this one, the way beyond
  // it (`routeCost`): a truck whose arm turns onto a ring only cars fit has a
  // first movement and nowhere after it. Not inserted, as SUMO discards what
  // it cannot insert; a later draw may choose a smaller vehicle.
  if (planFrom(w, vehicle) === null && w.graph.exitsOf(id).length > 0) {
    w.removeVehicle(vehicle);
    return false;
  }
  return true;
}

/**
 * Puts one vehicle of `arch` on lane `id` with its front at arc `s`, if
 * nothing on the lane is within a standstill gap of its body and nobody is
 * standing there, nor where the car behind could not keep its distance: the
 * scenery's way in (`sim/ambient`) - the cars of a map just opened, put on
 * its lanes at once (`AmbientWorld.open`), and with `?ambient=view` the cars
 * made where the camera does not look, as GTA does. Born at a cruise the car
 * ahead allows and slow enough to stop by its lane's end. Returns its id.
 */
export function spawnVehicleAt(w: SimWorld, id: string, s: number, arch: Archetype): number | null {
  const lane = w.lanelet(id);
  if (!lane || lane.kind !== 'link' || !w.graph.laneUsable(id, arch.shape)) return null;
  if (s < arch.length + 1 || s > lane.length - 1) return null;
  const rear = s - arch.length;
  let leaderGap = Infinity;
  let leaderSpeed = Infinity;
  let follower: Vehicle | null = null;
  let followerGap = Infinity;
  for (const body of w.bodiesIn(id)) {
    const front = body.s, back = body.s - body.vehicle.archetype.length;
    if (back - JAM_GAP < s && front + JAM_GAP > rear) return null;
    if (back >= s && back - s < leaderGap) { leaderGap = back - s; leaderSpeed = body.vehicle.v; }
    if (front <= rear && rear - front < followerGap) { followerGap = rear - front; follower = body.vehicle; }
  }
  for (const at of [rear, (rear + s) / 2, s]) {
    const f = lane.centre.sampleAt(Math.min(lane.length, Math.max(0, at)));
    if (w.pedEngine.bridge.anyoneWithin(w, f.p.x, f.p.y, arch.width / 2 + m(1), null)) return null;
  }
  const driver = makeDriver(arch, () => w.rng.driver.float());
  const v0 = lane.speedLimit * arch.speedFactor * w.rng.driver.range(DRIVER_NOISE.lo, DRIVER_NOISE.hi) * (1 + driver.aggression * 0.07);
  const color = arch.palette[Math.floor(w.rng.spawnVehicles.float() * arch.palette.length)] as string;
  // Born at a cruise the car ahead allows (SUMO's departSpeed "max", lowered
  // for a leader), and slow enough to stop in comfort by the end of its lane,
  // where a red or a give-way may be waiting (SUMO inserts a vehicle only if
  // "it can brake for upcoming non-prioritized intersections",
  // sumo.dlr.de/docs/Simulation/VehicleInsertion.html).
  const toEnd = Math.max(0, lane.length - s - driver.s0);
  const speed = Math.min(birthSpeed(driver, v0, v0 * w.rng.driver.range(0.6, 0.9), leaderGap, leaderSpeed),
    Math.sqrt(2 * driver.b * toEnd));
  // Nor in front of a car behind that could not keep its distance braking
  // in comfort ("followers are at a safe distance from it", ibid.).
  if (follower && idmAccel(follower.driver, follower.v, follower.v0,
    { gap: Math.max(0.01, followerGap), speed, kind: 'vehicle' as const }) < -follower.driver.b) return null;
  const vehicle = createVehicle(w.nextVehicleId++, arch, driver, color, id, v0, w.clock.tick);
  vehicle.s = s;
  vehicle.v = speed;
  // Nor faster than the bends ahead allow (SUMO inserts a vehicle only if it
  // can brake for what is ahead, ibid.): born in a bend at its cruise, it
  // took the bend 1 m/s over the speed its driver would ever drive it at
  // (`curvature.spec`, broken by the map filled at once on 2026-10-09).
  vehicle.v = Math.min(vehicle.v, curveSpeedCap(w, vehicle));
  vehicle.prev = snapshot(vehicle);
  assignOccupancy(w, vehicle);
  w.vehicles.set(vehicle.id, vehicle);
  w.enterLanelet(vehicle, id);
  vehicle.destination = chooseVehicleDestination(w, id, bodyClassOfArchetype(vehicle.archetype));
  // Nowhere this body can go from here - every way on too tight for it - and
  // it is not at a road's end: not inserted (SUMO discards what it cannot
  // insert). Born anyway, a truck at the arm of a ring only cars fit stood at
  // the end of its road for good, the arm queued behind it.
  if (planFrom(w, vehicle) === null && w.graph.exitsOf(id).length > 0) {
    w.removeVehicle(vehicle);
    return null;
  }
  return vehicle.id;
}

/**
 * How fast a vehicle arrives from off the map: its usual entry speed, unless
 * that would put it on the tail of the car ahead harder than its driver
 * brakes in comfort (audit P2-08). Measured on the test city, most of the
 * fleet's hard braking was cars born at speed two metres behind a slower one
 * - and braking at seven metres a second squared on their first tick.
 */
function birthSpeed(driver: ReturnType<typeof makeDriver>, v0: number, usual: number, gap: number, leaderSpeed: number): number {
  if (!Number.isFinite(gap)) return usual;
  const ahead = { gap: Math.max(0.01, gap), speed: Number.isFinite(leaderSpeed) ? leaderSpeed : 0, kind: 'vehicle' as const };
  if (idmAccel(driver, usual, v0, ahead) >= -driver.b) return usual;
  let lo = 0;
  let hi = usual;
  for (let i = 0; i < 16; i++) {
    const mid = (lo + hi) / 2;
    if (idmAccel(driver, mid, v0, ahead) >= -driver.b) lo = mid;
    else hi = mid;
  }
  return lo;
}

/**
 * Removes the vehicles that reached the end of a road and stopped there: the
 * only place a car leaves the map (the player's rule, 2026-10-06 - once made,
 * a car is never taken away anywhere else). It may also end its trip in a
 * lot, parked there (`agents/lotTraffic.ts`), and drive out again later.
 */
export function stepDespawn(w: SimWorld): void {
  for (const v of w.vehiclesInIdOrder()) {
    const lane = w.lanelet(v.lanelet);
    if (!lane) {
      w.removeVehicle(v);
      continue;
    }
    // The end-of-route obstacle brings a vehicle to rest at its standstill gap,
    // not against the very end of the lane, so the despawn threshold has to
    // allow for that — otherwise cars park just short of a map edge forever and
    // slowly plug the exit stub.
    const atEnd = lane.length - v.s < v.driver.s0 + 2;
    const body = bodyClassOfArchetype(v.archetype);
    const nowhereToGo = w.graph.exitsOf(v.lanelet).every((id) =>
      (w.connector(id)?.maxBodyClass ?? -1) < body);
    const roadEnd = lane.to !== undefined && w.doc.mapEdge(lane.to);
    // A car of the ambient traffic that may be on screen waits there: taken away out of sight.
    if (lane.kind === 'link' && atEnd && nowhereToGo && roadEnd && !w.ambient.sighted.has(v.id)) {
      if (v.destination === lane.id) w.completedTrips++;
      w.removeVehicle(v);
    }
  }
}

export { ARCHETYPES };
